config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  
  
  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :users
  get "signup" => "users#new"

  resource :session, only: [ :new, :create, :destroy ]
  get "sign-in" => "sessions#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  # validations
  validates :title, :released_on, :duration, presence: true

  validates :description, length: { minimum: 25 }

  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

  validates :image_file_name, format: { with: /\w+\.(jpg|png)\z/i, message: "must be a JPG or PNG image" }

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :rating, inclusion: { in: RATINGS }

  # methods
  def self.released
    where("released_on < ?", Time.now).order("released_on desc")
  end

  def self.hits
    where("total_gross >= 300000000").order(total_gross: :desc)
  end

  def self.flops
    where("total_gross < 225000000").order(total_gross: :asc)
  end

  def self.recently_added
    order(created_at: :desc).limit(3)
  end

  def flop?
    unless ( reviews.count > 50 && average_stars >= 4 )
      total_gross.blank? || total_gross < 225_000_000
    end
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def average_stars_as_percent
    (self.average_stars / 5) * 100
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :comment, length: { minimum: 4 }

  STARS = [ 1, 2, 3, 4, 5 ]
  validates :stars, inclusion: { in: STARS, message: "Must be between 1 and 5" }

  def stars_as_percent
    ( stars / 5.0 ) * 100.0
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  has_secure_password

  validates :name, presence: true
  
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 8, allow_blank: true }

  validates :username, presence: true, 
              format: { with: /\A[A-Z0-9]+\z/i },
              uniqueness: { case_sensitive: false }

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?
  
  def require_sign_in
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :require_sign_in
  before_action :set_movie

  def create
    @movie.favorites.create!(user: current_user)

    redirect_to @movie
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])
    favorite.destroy
    
    redirect_to @movie
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
before_action :require_sign_in, except: [:index, :show]
before_action :require_admin, except: [:index, :show]
before_action :set_movie, except: [:index, :new, :create]
  def index
    @movies = Movie.released
  end

  def show
    @fans = @movie.fans
    if current_user
      @favorite = current_user.favorites.find_by(movie_id: @movie.id)
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path, status: :see_other, alert: "Movie successfully deleted!"
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_sign_in
  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to movie_reviews_path(@movie), notice: "Thanks for your review"
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  private

  def review_params
    params.require(:review).permit(:stars, :comment)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email_or_username]) || User.find_by(username: params[:email_or_username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other, notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_sign_in, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
      @users = User.all 
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @favorite_movies = @user.favorite_movies
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other, alert: "Account successfully deleted!"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url, status: :see_other unless current_user?(@user) 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def fav_or_unfav_button(movie, favorite)
    if favorite 
      button_to "♡ Unfave", movie_favorite_path(movie, favorite), method: :delete 
    else
      button_to "♥️ Fave", movie_favorites_path(movie) 
    end 
  end
end

app/helpers/movies_helper.rb
module MoviesHelper

  def total_gross(movie)
    if movie.flop?
      "Flop!"
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  def year_of(movie)
    movie.released_on.year
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def profile_image(user, size=80)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}?s=#{size}"
    image_tag(url, alt: user.name)
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    &copy; <%= Time.now.year %>
    <%= link_to "MohamedHNoor", "#"%>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "Movies", movies_path %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Sing Out", session_path, data: {turbo_method: :delete}, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", sign_in_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Review Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <main class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f| %>
  <%= render "shared/errors", object: movie %>
  <%= f.label :title, autofocus: true %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description, rows: 10 %>
  <%= f.label :rating %>
  <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
  <%= f.label :released_on %>
  <%= f.date_select :released_on, {}, {class: "date"} %>
  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>
  <%= f.label :director %>
  <%= f.text_field :director %>
  <%= f.label :duration %>
  <%= f.text_field :duration %>
  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>
  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>
<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2><%= link_to movie.title, movie_path(movie)%></h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <span class="stars">
        <%= render "shared/stars", percent: movie.average_stars_as_percent %>
      </span>
      <p><%= truncate(movie.description, length: 150, separator: ' ')%></p>
    </div>
  </section>
<% end %>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Create a new Movie</h1>
<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
    <% if current_user %>
      <div class="faves">
        <%= fav_or_unfav_button(@movie, @favorite) %>
        <div class="count">
          <%= @fans.size %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <div class="reviews">
      <%= render "shared/stars", percent: @movie.average_stars_as_percent %>
      <%= link_to pluralize(@movie.reviews.size, "Review"), movie_reviews_path(@movie) %>
    </div>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Director:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td>
          <%= total_gross(@movie) %>
        </td>
      </tr>
    </table>
    <%= link_to "Write Review", new_movie_review_path(@movie), class: "review" %>
  </div>
  <aside>
    <% if @fans.present? %>
      <h4>Fans</h4>
      <ul>
        <% @fans.each do |user| %>
          <li>
            <%= profile_image(user, 35) %>
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </aside>
</section>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
    <%= link_to "Delete", movie_path(@movie), class: "button", data: {
    turbo_method: :delete, turbo_confirm: "Are you sure?"
  }%>
  </section>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: [movie, review]) do |f| %>
  <%= render "shared/errors", object: review %>
  <div class="legend">Stars</div>
  <% Review::STARS.each do |star| %>
    <span class="star">
      <%= f.radio_button :stars, star %>
      <%= f.label :stars, star, value: star %>
    </span>
  <% end %>
  <%= f.label :comment %>
  <%= f.text_area :comment, placeholder: "What did you think?" %>
  <%= f.submit "Post Review" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews for <%= link_to @movie.title, @movie %></h1>
<ul class="reviews">
  <% @reviews.each do |review| %>
    <li>
      <%= render "shared/stars", percent: review.stars_as_percent %>
      <p>
        <%= link_to review.user.name, review.user %>
        <span class="date">
          <%= time_ago_in_words(review.created_at) %> ago
        </span>
      </p>
      <p>
        <%= review.comment %>
      </p>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>
  New Review for
  <%= link_to @movie.title, @movie %>
</h1>
<%= render "form", movie: @movie , review: @review%>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
  <%= render "shared/errors", object: user %>
  <%= f.label :name  %>
  <%= f.text_field :name, autofocus: true %>
  <%= f.label :username  %>
  <%= f.text_field :username, placeholder: "Alphanumeric characters only!"%>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>
  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account"  %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>
  <%= pluralize(@users.size, "User") %>
</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <%= profile_image(@user) %>
  <h1>
    <%= @user.name %>
  </h1>
  <p>
    <%= @user.username %>
  </p>
  <h2>
    <%= mail_to(@user.email) %>
  </h2>
  <h3>Member Since</h3>
  <p>
    <%= @user.created_at.strftime("%B %Y") %>
  </p>
  <%# reviews %>
  <% if @reviews.present? %>
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
      <div class="review">
        <div class="details">
          <%= profile_image(review.user, 35) %>
          <span class="title">
            <%= link_to review.movie.title, review.movie %>
          </span>
          <%= pluralize(review.stars, 'star') %>
          <span class="date">
            <%= time_ago_in_words(review.created_at) %> ago
          </span>
          <p>
            <%= review.comment %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
  <%# favorite movie %>
  <% if @favorite_movies.present? %>
    <h3>Favorite Movies</h3>
    <div class="favorite-movies">
      <% @favorite_movies.each do |movie| %>
        <%= link_to image_tag(movie.image_file_name), movie %>
      <% end %>
    </div>
  <% end %>
  <%# actions %>
  <div class="actions">
    <% if current_user?(@user) %>
      <%= link_to "Edit Account", edit_user_path(@user), class: "button edit"%>
    <% end %>
    <% if current_user_admin? %>
      <%= link_to "Delete Account", @user, class: "button delete", data: {
      turbo_method: :delete, turbo_confirm: "Permanently delete your account!?"
    }%>
    <% end %>
  </div>
</section>